/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module DIG_Sub #(
    parameter Bits = 2
)
(
    input [(Bits-1):0] a,
    input [(Bits-1):0] b,
    input c_i,
    output [(Bits-1):0] s,
    output c_o
);
    wire [Bits:0] temp;

    assign temp = a - b - c_i;
    assign s = temp[(Bits-1):0];
    assign c_o = temp[Bits];
endmodule


module Mux_2x1_NBits #(
    parameter Bits = 2
)
(
    input [0:0] sel,
    input [(Bits - 1):0] in_0,
    input [(Bits - 1):0] in_1,
    output reg [(Bits - 1):0] out
);
    always @ (*) begin
        case (sel)
            1'h0: out = in_0;
            1'h1: out = in_1;
            default:
                out = 'h0;
        endcase
    end
endmodule


module divstage (
  input [31:0] divisor,
  input bitin,
  input [31:0] remin,
  output [31:0] remo,
  output qbit
);
  wire [31:0] s0;
  wire [31:0] s1;
  wire s2;
  assign s0[0] = bitin;
  assign s0[31:1] = remin[30:0];
  DIG_Sub #(
    .Bits(32)
  )
  DIG_Sub_i0 (
    .a( s0 ),
    .b( divisor ),
    .c_i( 1'b0 ),
    .s( s1 ),
    .c_o( s2 )
  );
  assign qbit = ~ s2;
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i1 (
    .sel( s2 ),
    .in_0( s1 ),
    .in_1( s0 ),
    .out( remo )
  );
endmodule

module DIG_Register_BUS #(
    parameter Bits = 1
)
(
    input C,
    input en,
    input [(Bits - 1):0]D,
    output [(Bits - 1):0]Q
);

    reg [(Bits - 1):0] state = 'h0;

    assign Q = state;

    always @ (posedge C) begin
        if (en)
            state <= D;
   end
endmodule

module SLL (
  input [31:0] in,
  input [4:0] shift,
  output [31:0] out
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire [31:0] s5;
  wire [31:0] s6;
  wire [31:0] s7;
  wire [31:0] s8;
  wire [31:0] s9;
  wire [31:0] s10;
  wire [31:0] s11;
  wire [31:0] s12;
  wire [31:0] s13;
  assign s5[0] = 1'b0;
  assign s5[31:1] = in[30:0];
  assign s0 = shift[0];
  assign s1 = shift[1];
  assign s2 = shift[2];
  assign s3 = shift[3];
  assign s4 = shift[4];
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i0 (
    .sel( s0 ),
    .in_0( in ),
    .in_1( s5 ),
    .out( s6 )
  );
  assign s7[1:0] = 2'b0;
  assign s7[31:2] = s6[29:0];
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i1 (
    .sel( s1 ),
    .in_0( s6 ),
    .in_1( s7 ),
    .out( s8 )
  );
  assign s9[3:0] = 4'b0;
  assign s9[31:4] = s8[27:0];
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i2 (
    .sel( s2 ),
    .in_0( s8 ),
    .in_1( s9 ),
    .out( s10 )
  );
  assign s11[7:0] = 8'b0;
  assign s11[31:8] = s10[23:0];
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i3 (
    .sel( s3 ),
    .in_0( s10 ),
    .in_1( s11 ),
    .out( s12 )
  );
  assign s13[15:0] = 16'b0;
  assign s13[31:16] = s12[15:0];
  Mux_2x1_NBits #(
    .Bits(32)
  )
  Mux_2x1_NBits_i4 (
    .sel( s4 ),
    .in_0( s12 ),
    .in_1( s13 ),
    .out( out )
  );
endmodule
