import sys


def parse_obj(filename, scale=20):
	vertices = []
	edges = set()

	with open(filename, "r") as f:
		for line in f:
			parts = line.strip().split()
			if not parts:
				continue

			if parts[0] == "v":
				# Extract x, y, z coordinates and scale them
				vx = float(parts[1]) * scale
				vy = float(parts[2]) * scale
				vz = float(parts[3]) * scale
				vertices.append((vx, vy, vz))

			elif parts[0] == "f":
				# Extract face indices (OBJ format is 1-indexed)
				face_indices = []
				for p in parts[1:]:
					idx = int(p.split("/")[0]) - 1
					face_indices.append(idx)

				# Create edges from the face polygon
				n = len(face_indices)
				for i in range(n):
					v1 = face_indices[i]
					v2 = face_indices[(i + 1) % n]
					edge = tuple(sorted((v1, v2)))
					edges.add(edge)

	# Center the model around its average coordinate center
	if vertices:
		min_x = min(v[0] for v in vertices)
		max_x = max(v[0] for v in vertices)
		min_y = min(v[1] for v in vertices)
		max_y = max(v[1] for v in vertices)
		min_z = min(v[2] for v in vertices)
		max_z = max(v[2] for v in vertices)

		cx = (min_x + max_x) / 2
		cy = (min_y + max_y) / 2
		cz = (min_z + max_z) / 2

		vertices = [(int(v[0] - cx), int(v[1] - cy), int(v[2] - cz)) for v in vertices]

	return vertices, list(edges)


def write_c_header(vertices, edges, output_filename="model_data.h"):
	with open(output_filename, "w") as f:
		f.write("// Auto-generated by obj2c.py\n")
		f.write("#ifndef MODEL_DATA_H\n")
		f.write("#define MODEL_DATA_H\n\n")

		f.write(f"#define NUM_VERTICES {len(vertices)}\n")
		f.write(f"#define NUM_EDGES {len(edges)}\n\n")

		f.write("struct Vec3 vertices[NUM_VERTICES] = {\n")
		for v in vertices:
			f.write("\t{" + f"{v[0]}, {v[1]}, {v[2]}" + "},\n")
		f.write("};\n\n")

		f.write("int edges[NUM_EDGES][2] = {\n")
		for e in edges:
			f.write("\t{" + f"{e[0]}, {e[1]}" + "},\n")
		f.write("};\n\n")

		f.write("#endif // MODEL_DATA_H\n")

	print(
		f"[+] Successfully generated '{output_filename}' with {len(vertices)} vertices and {len(edges)} edges!"
	)


if __name__ == "__main__":
	if len(sys.argv) < 2:
		print("Usage: python3 obj2c.py <model.obj> [scale]")
		sys.exit(1)

	obj_file = sys.argv[1]
	scale_val = float(sys.argv[2]) if len(sys.argv) > 2 else 20.0

	try:
		verts, edgs = parse_obj(obj_file, scale_val)
		write_c_header(verts, edgs)
	except Exception as e:
		print(f"[!] Error parsing OBJ file: {e}")